stages:
  - test
  - build
  - package
  - deploy
test:
  image: yeyudekuangxiang/go-test:latest
  stage: test
  tags:
    - test
  variables:
    TEST_ENV: real
    GO111MODULE: on
    GOPROXY: https://goproxy.cn,https://goproxy.io,direct
    CGO_ENABLED: 0
  before_script:
    - cat config.ini.example | sed "2c TokenKey=Yw9D7rQp485sUxNekgaLwMdkrpcFi1fElx" >> config.ini
    - /etc/init.d/mysql start
    - service mysql status
    - mysql -uroot -proot -e "grant all on *.* to root@'%' identified by 'root';flush privileges;"
    - mysql --user=root --password=root -e "CREATE DATABASE imagedesign charset=utf8mb4;"
    - mysql -uroot -proot imagedesign < ./mock/sql/imagedesign.sql
  script:
    - go mod download
    - cd tests
    - go test ./... -v
build:
  image: golang:1.17
  stage: build
  only:
    - develop
    - tags
  tags:
    - docker
  script:
    - env GOPROXY=https://goproxy.cn,https://goproxy.io,direct CGO_ENABLED=0 GOOS=linux GOARCH=amd64  go build .
  artifacts:
    paths:
      - imagedesign
package:
  stage: package
  only:
    - develop
    - tags
  tags:
    - shell
  dependencies:
    - build
  script:
    - docker build -t registry.cn-hangzhou.aliyuncs.com/jzl/imagedesign:$CI_COMMIT_REF_NAME -f ./build/Dockerfile .
    - docker login --username=jzl--password=$DOCKER_PWD registry.cn-hangzhou.aliyuncs.com
    - docker push registry.cn-hangzhou.aliyuncs.com/jzl/imagedesign:$CI_COMMIT_REF_NAME
deploy:
  image:
    name: bitnami/kubectl:1.20.10
    entrypoint: [""]
  stage: deploy
  only:
    - develop
    - tags
  tags:
    - docker
  before_script:
    - echo ${k8s_config} | base64 -d >> ./config-ali
    - export KUBECONFIG=$(pwd)/config-ali
  script:
    - bash ./build/deploy.sh $CI_COMMIT_REF_NAME